description: Example task
prompt: |-
      Pretend to be {name} and act as {name} who is a {role}

      {prompt}

      {instructions}
template: 
    system: |-
        You are impersonating characters for helping to write a book. Always act as the requested character.
ctx: 4096
model:
    name: qwen4b
    template: chatml
inferParams:
    top_k: 0.95
    top_p: 40
    min_p: 0
    temperature: 0.6
    max_tokens: 2048
variables:
    required:
        name:
            type: string
            description: The name of the character
        role:
            type: string
            description: The role of the character
    optional:
        instructions:
            type: string
            description: Optional additional instructions